version: '3'
services:
    web:
        build: .
        environment:
            REDIS_URL: redis://redis:6379
            MONGO_URL: mongodb://db:27017
            DB_NAME: museuamarantefc
            PORT: 8080
            EVENTS_IMAGES_PATH: /museuamarantefc_images
        depends_on:
            - redis
            - db
        ports: 
            - "8080:8080"
        volumes:
            - D:/museuamarantefc_images:/museuamarantefc_images
    redis:
        image: "redis"
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
    db:
        image: "mongo"
        ports:
            - "27018:27017"
        volumes:
            - mongodata:/data/db

volumes:
    mongodata:
    redisdata: